image:
  repository: outlinewiki/outline
  tag: 1.8.0

auth:
  oidc:
    enabled: true
    displayName: Local Dex
    authUri: http://dex.cluster.k8s/auth
    tokenUri: http://dex.cluster.k8s/token
    userInfoUri: http://de/userinfo
    clientId: outline
    clientSecret: outline-secret
    usernameClaim: email
    scopes:
      - openid
      - profile
      - email

secretKey: "6defbf8a571005ae08658d84046b563b6a990aaa189931cf9ae3e1f5d22e7188"
utilsSecret: "06ab808e915d575ee76a7526e74fbadfeb59ea9b04825454b823f1a7374be613"

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: outline.cluster.k8s
      paths:
        - path: /
          pathType: Prefix

postgresql:
  enabled: true
  architecture: standalone
  auth:
    username: outline
    password: "change-me-postgres-password"
    database: outline
    postgresPassword: "change-me-postgres-postgres-password"
  primary:
    persistence:
      enabled: true
      size: 5Gi

externalPostgresql:
  password: "change-me-postgres-password"

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    password: "change-me-redis-password"
  master:
    persistence:
      enabled: true
      size: 2Gi

minio:
  enabled: true
  rootUser: outline
  rootPassword: "change-me-minio-password"
  persistence:
    enabled: true
    size: 5Gi
    accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      memory: 256Mi
      cpu: 100m

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m

extraEnvVars: 
  - name: FORCE_HTTPS
    value: "false"