apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: outline
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://community-charts.github.io/helm-charts
      chart: outline
      targetRevision: 0.8.0
      helm:
        valueFiles:
          - $values/outline/values.yaml
    - repoURL: https://github.com/Nailloon/Programming-workshop
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true