ingress:
  enabled: true
  className: nginx
  hosts:
    - host: dex.cluster.k8s
      paths:
        - path: /
          pathType: Prefix

serviceAccount:
  create: true
  name: dex

config:
  issuer: http://dex.cluster.k8s
  storage:
    type: kubernetes
    config:
      inCluster: true
  web:
    http: "0.0.0.0:5556"
  oauth2:
    skipApprovalScreen: true
    alwaysShowLoginScreen: false
  enablePasswordDB: true
  staticClients:
    - id: outline
      name: Outline
      redirectURIs:
        - http://outline.cluster.k8s/auth/oidc.callback
      secret: outline-secret
  staticPasswords:
    - email: test@example.com
      hash: "$2a$10$CwTycUXWue0Thq9StjUM0uJ8S0Ksf5zWkD0dWKmYj4EO67F0z0iI2"
      username: test
      userID: "test-user"